// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhiPAfkcUkQKcNXCUUcKL51K5UqRd7WXA',
    appId: '1:372003342382:android:c33c6eb99da7ceb76fb7bf',
    messagingSenderId: '372003342382',
    projectId: 'hiddify-flutter',
    storageBucket: 'hiddify-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs7pee9vjdKfUYFbJvHo8rDwqp36dkPRI',
    appId: '1:372003342382:ios:a579c1abfc54046a6fb7bf',
    messagingSenderId: '372003342382',
    projectId: 'hiddify-flutter',
    storageBucket: 'hiddify-flutter.appspot.com',
    iosBundleId: 'com.hiddify.hiddify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs7pee9vjdKfUYFbJvHo8rDwqp36dkPRI',
    appId: '1:372003342382:ios:dd40035472392b346fb7bf',
    messagingSenderId: '372003342382',
    projectId: 'hiddify-flutter',
    storageBucket: 'hiddify-flutter.appspot.com',
    iosBundleId: 'com.hiddify.hiddify.RunnerTests',
  );
}
